apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore
        image: 084375547303.dkr.ecr.ap-south-1.amazonaws.com/my-app:2
        ports:
        - containerPort: 8081  # Change the container port to 8081
      imagePullSecrets:
      - name: ecr-secret
        
      
